config/routes.rb
Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"
  get 'dashboard/index'
  root to:'dashboard#index'

  resources :ratios
  resources :amounts
  resources :currencies do 
  	member do
  		post 'buy', to: 'currencies#buy'
      get 'open_modal', to:'currencies#open_modal'
  	end
    collection do
      get 'chart', to: 'currencies#gen_chart'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' =>'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/welcome' => 'welcome#new'


end

app/models/ratio.rb
class Ratio < ApplicationRecord
	belongs_to :currency
end

app/controllers/ratios_controller.rb
class RatiosController < ApplicationController
  before_action :set_ratio, only: [:show, :edit, :update, :destroy]

  # GET /ratios
  # GET /ratios.json
  def index
    @ratios = Ratio.all
  end

  # GET /ratios/1
  # GET /ratios/1.json
  def show
  end

  # GET /ratios/new
  def new
    @ratio = Ratio.new
  end

  # GET /ratios/1/edit
  def edit
  end

  # POST /ratios
  # POST /ratios.json
  def create
    @ratio = Ratio.new(ratio_params)

    respond_to do |format|
      if @ratio.save
        format.html { redirect_to @ratio, notice: 'Ratio was successfully created.' }
        format.json { render :show, status: :created, location: @ratio }
      else
        format.html { render :new }
        format.json { render json: @ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratios/1
  # PATCH/PUT /ratios/1.json
  def update
    respond_to do |format|
      if @ratio.update(ratio_params)
        format.html { redirect_to @ratio, notice: 'Ratio was successfully updated.' }
        format.json { render :show, status: :ok, location: @ratio }
      else
        format.html { render :edit }
        format.json { render json: @ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratios/1
  # DELETE /ratios/1.json
  def destroy
    @ratio.destroy
    respond_to do |format|
      format.html { redirect_to ratios_url, notice: 'Ratio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ratio
      @ratio = Ratio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ratio_params
      params.require(:ratio).permit(:currency_id, :value)
    end
end

app/helpers/ratios_helper.rb
module RatiosHelper
end

app/views/ratios/_form.html.erb
<%= form_with(model: ratio, local: true) do |form| %>
  <% if ratio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ratio.errors.count, "error") %> prohibited this ratio from being saved:</h2>

      <ul>
      <% ratio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :currency_id %>
    <%= form.number_field :currency_id, id: :ratio_currency_id %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :ratio_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ratios/edit.html.erb
<h1>Editing Ratio</h1>

<%= render 'form', ratio: @ratio %>

<%= link_to 'Show', @ratio %> |
<%= link_to 'Back', ratios_path %>

app/views/ratios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratios</h1>

<table>
  <thead>
    <tr>
      <th>Currency</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratios.each do |ratio| %>
      <tr>
        <td><%= ratio.currency_id %></td>
        <td><%= ratio.value %></td>
        <td><%= link_to 'Show', ratio %></td>
        <td><%= link_to 'Edit', edit_ratio_path(ratio) %></td>
        <td><%= link_to 'Destroy', ratio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ratio', new_ratio_path %>

app/views/ratios/new.html.erb
<h1>New Ratio</h1>

<%= render 'form', ratio: @ratio %>

<%= link_to 'Back', ratios_path %>

app/views/ratios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Currency:</strong>
  <%= @ratio.currency_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @ratio.value %>
</p>

<%= link_to 'Edit', edit_ratio_path(@ratio) %> |
<%= link_to 'Back', ratios_path %>