config/routes.rb
Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"
  get 'dashboard/index'
  root to:'dashboard#index'

  resources :ratios
  resources :amounts
  resources :currencies do 
  	member do
  		post 'buy', to: 'currencies#buy'
      get 'open_modal', to:'currencies#open_modal'
  	end
    collection do
      get 'chart', to: 'currencies#gen_chart'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' =>'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/welcome' => 'welcome#new'


end

app/models/currency.rb
class Currency < ApplicationRecord
	has_many :ratios

	def price(from_currency = nil)
		from_ratio = from_currency.nil? ? Currency.default_ratio : from_currency.ratios.last.ratio
		(from_ratio / current_ratio).round(3) 
		#se returneaza ultima linie
	end

	def current_ratio
		self.ratios.last.ratio
	end

	def self.default_ratio
		Currency.find_by(name: 'USD').ratios.last.ratio
	end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:open_modal, :buy, :show, :edit, :update, :destroy]
  before_action :authorize

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.where.not(default: true)
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  def buy
    #take params from modal
    final_currency_id = params[:final_currency_id]
    final_currency_amount = params[:final_currency_amount].to_f

    original_currency_id = params[:original_currency_id]
    cost = params[:cost].to_f


    #take the user current amount
    original_amount = Amount.find_by(user_id: current_user.id, currency_id: original_currency_id)
  
    if original_amount.quantity < cost then 
      #if the user doesn't have enough money to buy then
      redirect_to currencies_path, notice: "You don't have enough coins to buy"
    else
    #if there is enough quantity then 

      #check if user has allready an amount to that currency 
      final_amount = Amount.find_by(user_id: current_user.id, currency_id: final_currency_id)
      
      if final_amount then
        # update amount
        final_amount.update(
          quantity: final_amount.quantity + final_currency_amount
        )
      else
        #else create amount
        Amount.create(
          currency_id: final_currency_id,
          quantity: final_currency_amount,
          user_id: current_user.id
        )
      end

      #create transaction
      Transaction.create(
        user_id: current_user.id,
        original_currency_id: original_currency_id,
        original_currency_amount: original_amount.quantity,
        final_currency_id: final_currency_id,
        final_currency_amount: final_currency_amount
      )

      #update the quantity of the original amount
      if original_amount.quantity - cost == 0 then
        original_amount.destroy
      else
        original_amount.update(
            quantity: (original_amount.quantity - cost)
        )
      end
      
      redirect_to currencies_path, notice: 'Successfully bought some coins'
    end
  end

  def gen_chart
    data = []
    current_user.amounts.each do |amount|
      data << [amount.currency.name, amount.quantity * amount.currency.price]
    end
    render json:{currencies:data}
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  def open_modal
    @amount = params[:quantity].to_i

    render :partial => 'render_modal'    
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:name, :symbol, :default)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_currency_modal.html.erb
<div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
    <div class="modal-body">
    	<table class ="table">
    		<thead>
    			<th>Price: </th>
    			<th>Coin to buy</th>
    			<th>Action</th>
    		</thead>
    		<tbody>
		    	<% current_user.amounts.each do |amount| %>
			    	<tr>
				    	<td><%= amount.currency.name%> <%= @amount * @currency.price(amount.currency) %></td>
				    	<td><%= @currency.name %> <%= @amount %></td>
                        <td><%= link_to 'Buy', buy_currency_path(final_currency_id: @currency.id, original_currency_id: amount.currency.id, final_currency_amount: @amount, cost: @amount * @currency.price(amount.currency)), method: :post %></td>
			    	</tr>
			    <%end%>
	    	</tbody>
	    </table>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :currency_name %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :currency_symbol %>
  </div>

  <div class="field">
    <%= form.label :default %>
    <%= form.check_box :default, id: :currency_default %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currencies/_render_modal.js.erb
$("#currency-<%= @currency.id.to_s %>").html("<%= escape_javascript(render 'currency_modal') %>");
$("#currency-<%= @currency.id.to_s %>").modal('show');

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Currencies</h1>


<div id="chart"></div>

<table class = 'table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Amount to buy</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td><%= image_tag("#{currency.name.downcase.gsub(' ','_')}.svg", size: '23x23')%>
          <%= currency.name %>(<%=currency.symbol%>)</td>
        <td> <%= number_to_currency(currency.price) %> </td>

        <%= form_with url: open_modal_currency_path(currency.id),id:"buy-form-#{currency.id}" , method: :get do |form|%>
          <td> <%= form.number_field :quantity, min: 0.1, step: :any %></td>
          <td> <%= form.submit 'Buy', class: 'btn btn-primary',id:"buy-#{currency.id}" ,data: {disable_with: false} %></td>
        
        
        <% end %>
       
      </tr>
      <div class="modal fade" style="padding: 60px;" id="currency-<%= currency.id.to_s %>" tabindex="-1" role="dialog">
               <div class="modal-dialog" role="document">
               </div>
        </div>
    <% end %>
  </tbody>
</table>

<br>

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @currency.name %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @currency.symbol %>
</p>

<p>
  <strong>Default:</strong>
  <%= @currency.default %>
</p>

<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>