config/routes.rb
Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"
  get 'dashboard/index'
  root to:'dashboard#index'

  resources :ratios
  resources :amounts
  resources :currencies do 
  	member do
  		post 'buy', to: 'currencies#buy'
      get 'open_modal', to:'currencies#open_modal'
  	end
    collection do
      get 'chart', to: 'currencies#gen_chart'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' =>'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/welcome' => 'welcome#new'


end

app/models/amount.rb
class Amount < ApplicationRecord
	belongs_to :user 
	belongs_to :currency
end

app/controllers/amounts_controller.rb
class AmountsController < ApplicationController
  before_action :set_amount, only: [:show, :edit, :update, :destroy]

  # GET /amounts
  # GET /amounts.json
  def index
    @amounts = Amount.all
  end

  # GET /amounts/1
  # GET /amounts/1.json
  def show
  end

  # GET /amounts/new
  def new
    @amount = Amount.new
  end

  # GET /amounts/1/edit
  def edit
  end

  # POST /amounts
  # POST /amounts.json
  def create
    @amount = Amount.new(amount_params)

    respond_to do |format|
      if @amount.save
        format.html { redirect_to @amount, notice: 'Amount was successfully created.' }
        format.json { render :show, status: :created, location: @amount }
      else
        format.html { render :new }
        format.json { render json: @amount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amounts/1
  # PATCH/PUT /amounts/1.json
  def update
    respond_to do |format|
      if @amount.update(amount_params)
        format.html { redirect_to @amount, notice: 'Amount was successfully updated.' }
        format.json { render :show, status: :ok, location: @amount }
      else
        format.html { render :edit }
        format.json { render json: @amount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amounts/1
  # DELETE /amounts/1.json
  def destroy
    @amount.destroy
    respond_to do |format|
      format.html { redirect_to amounts_url, notice: 'Amount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amount
      @amount = Amount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amount_params
      params.require(:amount).permit(:user_id, :currency_id, :quantity)
    end
end

app/helpers/amounts_helper.rb
module AmountsHelper
end

app/views/amounts/_form.html.erb
<%= form_with(model: amount, local: true) do |form| %>
  <% if amount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amount.errors.count, "error") %> prohibited this amount from being saved:</h2>

      <ul>
      <% amount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :amount_user_id %>
  </div>

  <div class="field">
    <%= form.label :currency_id %>
    <%= form.number_field :currency_id, id: :amount_currency_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :amount_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/amounts/edit.html.erb
<h1>Editing Amount</h1>

<%= render 'form', amount: @amount %>

<%= link_to 'Show', @amount %> |
<%= link_to 'Back', amounts_path %>

app/views/amounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amounts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Currency</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amounts.each do |amount| %>
      <tr>
        <td><%= amount.user_id %></td>
        <td><%= amount.currency_id %></td>
        <td><%= amount.quantity %></td>
        <td><%= link_to 'Show', amount %></td>
        <td><%= link_to 'Edit', edit_amount_path(amount) %></td>
        <td><%= link_to 'Destroy', amount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amount', new_amount_path %>

app/views/amounts/new.html.erb
<h1>New Amount</h1>

<%= render 'form', amount: @amount %>

<%= link_to 'Back', amounts_path %>

app/views/amounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @amount.user_id %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @amount.currency_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @amount.quantity %>
</p>

<%= link_to 'Edit', edit_amount_path(@amount) %> |
<%= link_to 'Back', amounts_path %>