config/routes.rb
Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"
  get 'dashboard/index'
  root to:'dashboard#index'

  resources :ratios
  resources :amounts
  resources :currencies do 
  	member do
  		post 'buy', to: 'currencies#buy'
      get 'open_modal', to:'currencies#open_modal'
  	end
    collection do
      get 'chart', to: 'currencies#gen_chart'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' =>'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/welcome' => 'welcome#new'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aclabs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="row">
       <div class="col-lg-12">
         <nav class="navbar navbar-default">
           <div class="container-fluid">              
            <div class="navbar-header">
               <%= link_to 'Cryptocurrencies meet Ruby', root_path, class: 'navbar-brand' %>
             </div>              
             <% if current_user %>                
              <ul class="nav navbar-nav">
                 <li><%= link_to 'Welcome', welcome_path %></li>
                 <li><%= link_to 'Currencies', currencies_path %></li>
              </ul>                
              <ul class="nav navbar-nav navbar-right">
                 <li><%= link_to 'Logout', logout_path%></li>
              </ul>
               <p class="navbar-text navbar-right">
                 Welcome, <%= current_user.name %>.
               </p>
             <% else %>
               <ul class="nav navbar-nav navbar-right" style = "margin-right:50px">
                <div class = "container-fluid">
                 <li><br>
                  <%= form_tag do %>
                         
                          <%= label_tag :name,'Name:'%>
                          <%= text_field_tag :name, '',:class => 'form_control text_center'%>
                          
                          <%= label_tag :password, 'Password:'%>
                          <%= text_field_tag :password, '',:class => 'form_control text_center'%>
                        
                          <%= submit_tag "Login", :class => 'btn btn-primary' %>

                          </li>
                  <%end%>
                
                  <li>Don't have an account? Please 
                          <%= link_to 'Sign up', signup_path, class: 'btn btn-link' %></li>
                  </div>
                </ul>
             <% end %>            
           </div><!-- /.container-fluid -->
         </nav>
       </div>
    </div>
  	<div class="container" >
    	   <%= yield %>
    </div>
  </body>
</html>